#!/bin/bash

curl -i \
    -H "Accept: application/json" \
    -H 'Content-Type: application/json' \
    -X POST -d '{"phase": "phase1", "aux": {}, "user_input": "yes"}' \
    http://localhost:3000/ask
